# Generated by Django 4.2.11 on 2024-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brunchin_Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foot_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('food_type', models.CharField(max_length=255)),
                ('food_restaurant', models.CharField(max_length=255)),
                ('food_items', models.CharField(max_length=255)),
                ('food_img', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
