# Generated by Django 4.2.11 on 2024-05-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brunchin_Food', '0003_rename_food_items_foot_category_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='brunch_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('fo_name', models.CharField(max_length=255)),
                ('fo_type', models.CharField(max_length=255)),
                ('fo_price', models.CharField(max_length=255)),
                ('fo_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
