# Generated by Django 4.2.11 on 2024-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brunchin_Food', '0004_brunch_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brunch_cart',
            name='fo_price',
            field=models.IntegerField(),
        ),
    ]
